audit_header: false
title: Puget Sound Real Estate Video Blog with Kwasi Bowie
description: Our mission at Kwasi Homes is to be your best resource for Puget Sound real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Kwasi Homes, your professional Puget Sound Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Local Businesses
    url: /local-businesses/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Kwasi Bowie
  title:
  license_number:
  about_markdown: |
    Kwasi Bowie has been making a name for himself in the Real Estate industry since 2007. He has set a standard of excellence by truly dedicating himself to his craft. He has a full-time team of well-trained real estate professionals who continuously strive to provide top quality service to clients and customers. Kwasi Homes specializes in listing and selling of residential housing, new home sites and investment opportunities.

    Whether you're looking for a new home to reside in, or searching for the next addition to your investment portfolio; Kwasi and his team is ready to assist you!
  brand: Kwasi Homes
  brokerage: John L. Scott INC.
  market: Puget Sound
  address: 6040 California Ave SW Suite C, Seattle, WA 98136
  phone: 206-854-4132
  phone_type:
  phone2:
  phone2_type:
  email: kwasib@kwasihomes.com
  url: https://www.kwasihomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.kwasihomes.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.kwasihomes.com/results/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Puget Sound Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.kwasihomes.com/home-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Puget Sound Home?"
    CTA_text2: "Search the entire MLS for your Puget Sound home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.kwasihomes.com/results/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/KwasiHomes
  linkedin_url: https://www.linkedin.com/in/kwasi-bowie-8095a312/
  youtube_url: https://www.youtube.com/channel/UCQSgtbSeee1rl9UQBUfLBMA
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/kwasib/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Puget Sound Real Estate Podcast with Kwasi Bowie'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Puget Sound Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Kwasi Homes - your professional Puget Sound Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Puget Sound, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Kwasi Bowie'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Puget Sound Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#999'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
